
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/rnjwplayer/Props.h>
#include <folly/dynamic.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

RNJWPlayerProps::RNJWPlayerProps(
    const PropsParserContext &context,
    const RNJWPlayerProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    config(convertRawProp(context, rawProps, "config", sourceProps.config, {})),
    controls(convertRawProp(context, rawProps, "controls", sourceProps.controls, {false}))
      {}

} // namespace react
} // namespace facebook
